### ISSUE TITLE
Does not work with vue2

### ISSUE THREAD

**Issue by mheers** [wobsoriano/vuemoji-picker#7]
Unfortunately it does not work with vue2 in the current version.

I created a very simple demo project using `vue-cli-service`:
https://github.com/mheers/vuemoji-picker-error

The cli does not report any errors, but the browsers console says:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'ignoredElements')
    at eval (webpack-internal:///./node_modules/vuemoji-picker/dist/index.mjs:77:56)
    at Module../node_modules/vuemoji-picker/dist/index.mjs (chunk-vendors.js:1548:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/HelloWorld.vue?vue&type=script&lang=js&:2:72)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/HelloWorld.vue?vue&type=script&lang=js& (app.js:950:1)
    at __webpack_require__ (app.js:849:30)
    at fn (app.js:151:20)
    at eval (webpack-internal:///./src/components/HelloWorld.vue?vue&type=script&lang=js&:2:286)
    at Module../src/components/HelloWorld.vue?vue&type=script&lang=js& (app.js:1112:1)
```

**Comment by mheers** [comment]
It seems like it depends on the versions of the `devDependencies`:

This works with `v0.1.4`:
```json
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
```

And this does not work:
```json
    "@vue/cli-plugin-babel": "^4.5.14",
    "@vue/cli-plugin-eslint": "^4.5.14",
    "@vue/cli-plugin-typescript": "^4.5.14",
    "@vue/cli-service": "^4.5.14",
```

**Comment by wobsoriano** [comment]
https://github.com/vueuse/vue-demi/issues/152
